/**
 * site-scanner bookmarklet
 * 実行: ブラウザのブックマークに以下のURLをセット
 * ページ構造JSONをWorker経由でGitHubに保存する
 *
 * SCAN_ENDPOINT: pfd-coupon-fetcher Worker の /scan エンドポイント
 */

const SCAN_ENDPOINT = "https://pfd-coupon-fetcher.purple-voice-a554.workers.dev/scan?secret=pfd-secret-2026";

// ─── ブックマークレット本体（以下をそのままブックマークのURLに貼る）───

javascript:void((function(){'use strict';
const ENDPOINT='https://pfd-coupon-fetcher.purple-voice-a554.workers.dev/scan?secret=pfd-secret-2026';
const MAX_TREE_DEPTH=3;const MAX_REPEAT_PATTERNS=20;const MAX_INTERACTIVE=200;const MAX_TABLES=30;const MAX_CSS_VARS=100;const MAX_EXTERNAL=50;
function getSel(el){var parts=[];while(el&&el!==document.body&&el!==document.documentElement){var s=el.tagName.toLowerCase();if(el.id)s+='#'+el.id;else if(el.className&&typeof el.className==='string'){var c=el.className.trim().split(/\s+/).slice(0,3).join('.');if(c)s+='.'+c;}parts.unshift(s);el=el.parentElement;}return parts.join(' > ');}
function getAttrs(el){var o={};for(var i=0;i<el.attributes.length;i++){var a=el.attributes[i];if(a.name.startsWith('data-'))o[a.name]=a.value;}return Object.keys(o).length?o:undefined;}
function getMeta(){var m={url:location.href,title:document.title};var desc=document.querySelector('meta[name="description"]');if(desc)m.description=desc.content;var og=['og:title','og:description','og:image','og:url','og:type'];var ogp={};og.forEach(function(n){var el=document.querySelector('meta[property="'+n+'"]');if(el)ogp[n]=el.content;});if(Object.keys(ogp).length)m.ogp=ogp;var vp=document.querySelector('meta[name="viewport"]');if(vp)m.viewport=vp.content;return m;}
function buildTree(el,depth){if(depth>MAX_TREE_DEPTH)return null;var children=Array.from(el.children);var node={tag:el.tagName.toLowerCase(),childCount:children.length};if(el.id)node.id=el.id;if(el.className&&typeof el.className==='string'){var cls=el.className.trim();if(cls)node.class=cls;}if(el.getAttribute('role'))node.role=el.getAttribute('role');var da=getAttrs(el);if(da)node.data=da;if(depth<MAX_TREE_DEPTH&&children.length>0){node.children=children.slice(0,50).map(function(c){return buildTree(c,depth+1);}).filter(Boolean);}return node;}
function getSemantic(){var tags=['header','nav','main','aside','footer','section','article'];var r={};tags.forEach(function(t){var els=document.querySelectorAll(t);if(els.length){r[t]={count:els.length,selectors:Array.from(els).slice(0,5).map(getSel)};}});return r;}
function getInteractive(){var sels=['button','a[href]','input','select','textarea','[onclick]','[data-action]','[role="button"]','[role="link"]','[role="tab"]','[role="menuitem"]'];var all=[];sels.forEach(function(s){try{var els=document.querySelectorAll(s);els.forEach(function(el){if(all.length>=MAX_INTERACTIVE)return;var item={tag:el.tagName.toLowerCase(),selector:getSel(el)};var txt=(el.textContent||'').trim().substring(0,80);if(txt)item.text=txt;if(el.type)item.type=el.type;if(el.href)item.href=el.href.substring(0,200);if(el.name)item.name=el.name;if(el.getAttribute('data-action'))item.dataAction=el.getAttribute('data-action');all.push(item);});}catch(e){}});return all;}
function getTables(){var tables=document.querySelectorAll('table');var r=[];Array.from(tables).slice(0,MAX_TABLES).forEach(function(t){var item={selector:getSel(t)};var thead=t.querySelector('thead');if(thead){item.headers=Array.from(thead.querySelectorAll('th,td')).map(function(c){return(c.textContent||'').trim().substring(0,60);});}var rows=t.querySelectorAll('tbody tr, tr');item.rowCount=rows.length;r.push(item);});return r;}
function getRepeatingPatterns(){var classCount={};var allEls=document.body.querySelectorAll('*');for(var i=0;i<allEls.length;i++){var el=allEls[i];if(el.className&&typeof el.className==='string'){var cls=el.className.trim();if(!cls)continue;if(!classCount[cls])classCount[cls]={count:0,tag:el.tagName.toLowerCase(),sample:null};classCount[cls].count++;if(!classCount[cls].sample){classCount[cls].sample=(el.innerText||'').trim().substring(0,100);}}}var patterns=[];for(var k in classCount){if(classCount[k].count>=5){patterns.push({class:k,tag:classCount[k].tag,count:classCount[k].count,sampleText:classCount[k].sample});}}patterns.sort(function(a,b){return b.count-a.count;});return patterns.slice(0,MAX_REPEAT_PATTERNS);}
function getShadowAndIframe(){var iframes=document.querySelectorAll('iframe');var iframeInfo=Array.from(iframes).slice(0,10).map(function(f){var info={selector:getSel(f),src:f.src||'(none)'};try{var d=f.contentDocument;info.accessible=!!d;}catch(e){info.accessible=false;}return info;});var shadowHosts=[];var walk=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT);var count=0;while(walk.nextNode()&&count<10000){count++;if(walk.currentNode.shadowRoot){shadowHosts.push({selector:getSel(walk.currentNode),tag:walk.currentNode.tagName.toLowerCase(),mode:walk.currentNode.shadowRoot.mode||'unknown'});if(shadowHosts.length>=10)break;}}return{iframes:iframeInfo,shadowDom:shadowHosts};}
function getCssVars(){var vars={};try{var styles=getComputedStyle(document.documentElement);var sheets=document.styleSheets;for(var i=0;i<sheets.length;i++){try{var rules=sheets[i].cssRules||[];for(var j=0;j<rules.length;j++){if(rules[j].selectorText===':root'||rules[j].selectorText==='html'){var txt=rules[j].cssText;var matches=txt.match(/--[\w-]+/g);if(matches){matches.forEach(function(v){if(Object.keys(vars).length<MAX_CSS_VARS){vars[v]=styles.getPropertyValue(v).trim();}});}}}}}catch(e){}}catch(e){}return vars;}
function getExternalResources(){var scripts=Array.from(document.querySelectorAll('script[src]')).slice(0,MAX_EXTERNAL).map(function(s){return s.src;});var styles=Array.from(document.querySelectorAll('link[rel="stylesheet"]')).slice(0,MAX_EXTERNAL).map(function(l){return l.href;});return{scripts:scripts,styles:styles};}
function getDataAttributes(){var attrMap={};var allEls=document.body.querySelectorAll('*');for(var i=0;i<allEls.length;i++){var el=allEls[i];for(var j=0;j<el.attributes.length;j++){var a=el.attributes[j];if(a.name.startsWith('data-')){if(!attrMap[a.name])attrMap[a.name]={count:0,sampleValues:[]};attrMap[a.name].count++;if(attrMap[a.name].sampleValues.length<3&&a.value){attrMap[a.name].sampleValues.push(a.value.substring(0,80));}}}}var arr=[];for(var k in attrMap){arr.push({name:k,count:attrMap[k].count,sampleValues:attrMap[k].sampleValues});}arr.sort(function(a,b){return b.count-a.count;});return arr.slice(0,50);}
function showToast(msg,color){var d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;bottom:24px;right:24px;background:#1a1a2e;color:'+(color||'#0f0')+';padding:12px 20px;border-radius:8px;font-family:monospace;font-size:14px;z-index:999999;box-shadow:0 4px 12px rgba(0,0,0,.5);border:1px solid #0f03;transition:opacity .5s;';document.body.appendChild(d);setTimeout(function(){d.style.opacity='0';},2500);setTimeout(function(){d.remove();},3200);}
var result={_tool:'site-scanner',_version:'1.0',_url:location.href,_at:new Date().toISOString(),meta:getMeta(),structure:{tree:buildTree(document.body,0),semantic:getSemantic()},interactive:getInteractive(),tables:getTables(),repeatingPatterns:getRepeatingPatterns(),shadowDom:getShadowAndIframe(),cssVars:getCssVars(),externalResources:getExternalResources(),dataAttributes:getDataAttributes()};
var defaultSlug=location.hostname.replace('www.','').split('.')[0];
var slug=prompt('firmSlug?',defaultSlug)||defaultSlug;
showToast('📡 送信中: '+slug,'#f0b90b');
fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmSlug:slug,data:result})}).then(function(r){return r.json();}).then(function(){showToast('✅ 保存完了: data/scans/'+slug+'.json');}).catch(function(e){showToast('❌ 失敗: '+e.message,'#ef4444');});
})())
